`timescale 1ns/1ps

module tb_t81_top;
    localparam int OP_NOP    = 0;
    localparam int OP_PASSA  = 1;
    localparam int OP_ADD    = 2;
    localparam int OP_SUB    = 3;
    localparam int OP_NEG    = 4;
    localparam int OP_MIN    = 5;
    localparam int OP_MAX    = 6;
    localparam int OP_ISZERO = 7;

    logic [2:0] opcode;
    logic signed [1:0] trit_a;
    logic signed [1:0] trit_b;
    logic signed [1:0] trit_y;
    logic valid;

    int fd;
    int rc;
    int line_no;
    int exp_valid;
    int exp_y;
    int op_i;
    int a_i;
    int b_i;
    int got_y;
    int got_valid;
    /* verilator lint_off UNUSEDSIGNAL */
    reg [8*256-1:0] header_line;
    /* verilator lint_on UNUSEDSIGNAL */

    t81_top dut (
        .opcode(opcode),
        .trit_a(trit_a),
        .trit_b(trit_b),
        .trit_y(trit_y),
        .valid(valid)
    );

    function automatic int clamp_trit(input int value);
        if (value > 1) begin
            clamp_trit = 1;
        end else if (value < -1) begin
            clamp_trit = -1;
        end else begin
            clamp_trit = value;
        end
    endfunction

    function automatic int min_trit(input int a, input int b);
        min_trit = (a < b) ? a : b;
    endfunction

    function automatic int max_trit(input int a, input int b);
        max_trit = (a > b) ? a : b;
    endfunction

    function automatic int model_y(input int op, input int a, input int b);
        case (op)
            OP_NOP:    model_y = 0;
            OP_PASSA:  model_y = clamp_trit(a);
            OP_ADD:    model_y = clamp_trit(a + b);
            OP_SUB:    model_y = clamp_trit(a - b);
            OP_NEG:    model_y = clamp_trit(-a);
            OP_MIN:    model_y = clamp_trit(min_trit(a, b));
            OP_MAX:    model_y = clamp_trit(max_trit(a, b));
            OP_ISZERO: model_y = (a == 0) ? 1 : -1;
            default:   model_y = 0;
        endcase
    endfunction

    function automatic int model_valid(input int op);
        model_valid = (op >= OP_NOP && op <= OP_ISZERO) ? 1 : 0;
    endfunction

    task automatic check_case(input int op, input int a, input int b, input int expect_y, input int expect_valid, input [8*16-1:0] src);
        opcode = op[2:0];
        trit_a = $signed(a[1:0]);
        trit_b = $signed(b[1:0]);
        #1;

        if (valid !== 1'b0 && valid !== 1'b1) begin
            $display("FAIL [%0s] valid is X/Z", src);
            $fatal(1);
        end

        if (!($signed(trit_y) >= -1 && $signed(trit_y) <= 1)) begin
            $display("FAIL [%0s] trit_y out of range: %0d", src, $signed(trit_y));
            $fatal(1);
        end

        if (trit_y == -2'sd1) begin
            got_y = -1;
        end else if (trit_y == 2'sd1) begin
            got_y = 1;
        end else begin
            got_y = 0;
        end
        got_valid = (valid == 1'b1) ? 1 : 0;

        if (got_y != expect_y || got_valid != expect_valid) begin
            $display("FAIL [%0s] op=%0d a=%0d b=%0d got(y=%0d valid=%0d) exp(y=%0d valid=%0d)",
                src, op, a, b, got_y, got_valid, expect_y, expect_valid);
            $fatal(1);
        end
    endtask

    initial begin
        line_no = 0;

        // Exhaustive local model checks.
        for (op_i = 0; op_i <= 7; op_i = op_i + 1) begin
            for (a_i = -1; a_i <= 1; a_i = a_i + 1) begin
                for (b_i = -1; b_i <= 1; b_i = b_i + 1) begin
                    check_case(op_i, a_i, b_i, model_y(op_i, a_i, b_i), model_valid(op_i), "tb-model");
                end
            end
        end

        // Golden vectors generated by emulator/reference model.
        fd = $fopen("sim/vectors/t81_top_vectors.tsv", "r");
        if (fd == 0) begin
            $display("FAIL: could not open sim/vectors/t81_top_vectors.tsv");
            $fatal(1);
        end

        // Skip header line.
        rc = $fgets(header_line, fd);
        while (!$feof(fd)) begin
            rc = $fscanf(fd, "%d\t%d\t%d\t%d\t%d\n", op_i, a_i, b_i, exp_y, exp_valid);
            if (rc == 5) begin
                line_no = line_no + 1;
                check_case(op_i, a_i, b_i, exp_y, exp_valid, "vector");
            end
        end
        $fclose(fd);

        $display("PASS: checked %0d vector rows plus exhaustive model coverage", line_no);
        $finish;
    end
endmodule
